#!/bin/sh
MACHDIR="$1"
shift
cd "$MACHDIR"
if [[ -f .vscode/mach-result.json ]] ; then
    rm .vscode/mach-result.json
fi
./mach "$@"
MACHRESULT="$?"
echo "{\"code\": $MACHRESULT}" > .vscode/mach-result.json
