#!/bin/bash
# A script to ensure that, after we build, we regenerate the CompileDB so that
# vs code can complete things properly
# TODO - make this work on windows!

cd "$1"
./mach --log-no-times build

./mach build-backend -b CompileDB

# This gets rid of ccache references, which causes vscode to choke
# TODO - get appropriate objdir here
sed -e "s/\/usr\/local\/bin\/ccache //g" < obj-dbg/compile_commands.json > obj-dbg/compile_commands_new.json
mv obj-dbg/compile_commands_new.json obj-dbg/compile_commands.json

# TODO (maybe) - turn objdir/mozilla-config.h into something for c_cpp_properties.json?
